# Generated by Django 4.1.5 on 2023-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="duration",
            field=models.DurationField(),
        ),
    ]
