# Generated by Django 4.1.5 on 2023-01-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_alter_route_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={"ordering": ["type"], "verbose_name_plural": "aircraft"},
        ),
        migrations.AlterModelOptions(
            name="designbureau",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["departure"]},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["departure_airport"]},
        ),
        migrations.AlterField(
            model_name="flight",
            name="aircraft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="flight.aircraft",
            ),
        ),
    ]
