# Generated by Django 4.1.5 on 2023-02-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_alter_aircraft_options_alter_designbureau_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crewmember",
            options={"ordering": ["username"]},
        ),
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="flight.route",
            ),
        ),
    ]
